@startuml
actor user  as u

node Kubernetes as kube {
  port p1
  node "App Node" as app_n{
    node pods as ps {
        node frontend as p_fo
        node backend as p_be
    }
  }

  node cert_manager {
    rectangle www as tls_www
    rectangle api as tls_api
  }
  node ingress_controller as nginx {
      package ingress {
        rectangle www as in_www
        rectangle api as in_api
      }

      in_www --> tls_www
      in_api --> tls_api
  }

  in_www --> p_fo
  in_api --> p_be
}

u ----> p1
p1 ----> nginx
@enduml